version: '3.8'

services:
  synctime:
    build: .
    container_name: synctime_app
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - synctime_data:/app/server/db_data
    environment:
      - NODE_ENV=production
      - PORT=3001
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}

volumes:
  synctime_data:
